In [4]:
import math


for i in range(-10, 10, 5):
    print(1/(1+math.e**(-i)))

4.539786870243442e-05
0.006692850924284857
0.5
0.9933071490757153


In [15]:
import torch

def trans_conv(X, K, stride):
    h, w = K.shape
    Y = torch.zeros(((X.shape[0] + h - 1) * stride, (X.shape[1] + w -1) * stride))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i*stride: i*stride + h, j*stride:j*stride+w] += X[i, j] * K
            print(Y)
    return Y

In [16]:
X = torch.tensor([[0, 1], [2, 3]])
K = torch.tensor([[0, 1], [2, 3]])

trans_conv(X, K, 2)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 1., 0., 0.],
        [0., 0., 2., 3., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 1., 0., 0.],
        [0., 0., 2., 3., 0., 0.],
        [0., 2., 0., 0., 0., 0.],
        [4., 6., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 1., 0., 0.],
        [0., 0., 2., 3., 0., 0.],
        [0., 2., 0., 3., 0., 0.],
        [4., 6., 6., 9., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


tensor([[0., 0., 0., 1., 0., 0.],
        [0., 0., 2., 3., 0., 0.],
        [0., 2., 0., 3., 0., 0.],
        [4., 6., 6., 9., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [17]:
import torch

def trans_conv(X, K, stride=2, padding=1):
    h, w = K.shape
    # Padding the input with a border of zeros
    X_padded = torch.zeros((X.shape[0] + 2 * padding, X.shape[1] + 2 * padding))
    X_padded[padding:-padding, padding:-padding] = X

    # Output size: applying transposed convolution with stride
    Y = torch.zeros((X_padded.shape[0] - 1) * stride + h, (X_padded.shape[1] - 1) * stride + w)
    
    # Apply transposed convolution with stride and padding
    for i in range(X_padded.shape[0]):
        for j in range(X_padded.shape[1]):
            Y[i * stride: i * stride + h, j * stride: j * stride + w] += X_padded[i, j] * K
    return Y

# Example input (2x2)
X = torch.tensor([[1, 2], [3, 4]])

# 3x3 kernel
K = torch.tensor([[0, 1, 2], 
                  [3, 4, 5], 
                  [6, 7, 8]])

# Perform transpose convolution with stride=2, padding=1
output = trans_conv(X, K, stride=2, padding=1)
print(output)

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  2.,  2.,  4.,  0.,  0.],
        [ 0.,  0.,  3.,  4., 11.,  8., 10.,  0.,  0.],
        [ 0.,  0.,  6., 10., 26., 18., 24.,  0.,  0.],
        [ 0.,  0.,  9., 12., 27., 16., 20.,  0.,  0.],
        [ 0.,  0., 18., 21., 48., 28., 32.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
